version: '2'

networks:
  api-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  mongo:
    container_name: ${APP_TITLE}-${DB_NAME}
    image: ${APP_TITLE}/mongo
    labels:
      com.singularjs.db: ${DB_NAME}
    build:
      context: .
      dockerfile: ./docker/dockerfiles/${NODE_ENV}/mongo.dockerfile
    command: "--auth"
    expose:
      - "27017"
    volumes:
      - /data/${DB_PATH}:/data/${DB_NAME}:rw

  api:
    container_name: ${APP_TITLE}-api
    image: ${APP_TITLE}/api
    build:
      context: .
      dockerfile: ./docker/dockerfiles/${NODE_ENV}/api.dockerfile
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - "./api/dev/root.js:/usr/app/root.js"
      - "./public:/public"
    env_file:
      - ./docker/env/${NODE_ENV}/api.env
    environment:
      - NODE_ENV=${NODE_ENV}
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "1"

  upload:
    container_name: ${APP_TITLE}-upload
    image: ${APP_TITLE}/upload
    build:
      context: .
      dockerfile: ./docker/dockerfiles/${NODE_ENV}/upload.dockerfile
    depends_on:
      - mongo
    ports:
      - "3001:3000"
    volumes:
      - "./upload/dev/root.js:/usr/app/root.js"
      - "./public:/public"
    env_file:
      - ./docker/env/${NODE_ENV}/upload.env
    environment:
      - NODE_ENV=${NODE_ENV}
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "1"
