version: '2'

networks:
  data:
    driver: bridge

  web:
    driver: bridge

services:
  mongo:
    container_name: ${APP_TITLE}-${DB_NAME}
    image: ${APP_TITLE}/mongo
    labels:
      com.singularjs.db: ${DB_NAME}
    build:
      context: .
      dockerfile: ./docker/dockerfiles/${NODE_ENV}/mongo.dockerfile
    command: "--auth"
    expose:
      - "27017"
    volumes:
      - /data/${DB_PATH}:/data/${DB_NAME}:rw
    networks:
      - data

  api:
    container_name: ${APP_TITLE}-api
    image: ${APP_TITLE}/api
    build:
      context: .
      dockerfile: ./docker/dockerfiles/${NODE_ENV}/api.dockerfile
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    env_file:
      - ./docker/env/${NODE_ENV}/api.env
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - "./api/dev/root.js:/usr/app/root.js"
      - "./public:/public"
    working_dir: "/usr/app"
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "1"
    networks:
      - data
      - web

  upload:
    container_name: ${APP_TITLE}-upload
    image: ${APP_TITLE}/upload
    build:
      context: .
      dockerfile: ./docker/dockerfiles/${NODE_ENV}/upload.dockerfile
    depends_on:
      - mongo
    ports:
      - "3001:3000"
    env_file:
      - ./docker/env/${NODE_ENV}/upload.env
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - "./upload/dev/root.js:/usr/app/root.js"
      - "./public:/public"
    working_dir: "/usr/app"
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "1"
    networks:
      - web

  platform:
    container_name: ${APP_TITLE}-platform
    image: ${APP_TITLE}/platform
    build:
      context: .
      dockerfile: ./docker/dockerfiles/${NODE_ENV}/platform.dockerfile
    depends_on:
      - api
    ports:
      - "8082:80"
    volumes:
      - "./docker/config/development/platform.conf:/etc/nginx/nginx.conf"
      - "./platform/dev:/usr/share/nginx/html"
    working_dir: "/usr/share/nginx/html"
    networks:
      - web
