export const UNKNOWN: string = 'UNKNOWN_ERROR'

export const ACTION = {
  ACTION_CREATOR_REQUIRED: 'ACTION_CREATOR_REQUIRED',
  ACTION_TARGET_REQUIRED: 'ACTION_TARGET_REQUIRED',
  ACTION_TARGET_NOT_SPECIFIED: 'ACTION_TARGET_NOT_SPECIFIED',
  ACTION_TARGET_NOT_FOUND: 'ACTION_TARGET_NOT_FOUND',
  ACTION_TYPE_REQUIRED: 'ACTION_TYPE_REQUIRED',
  ACTION_TYPE_NOT_FOUND: 'ACTION_TYPE_NOT_FOUND',
  ACTION_NOT_AUTHORIZED: 'ACTION_NOT_AUTHORIZED',
  CANNOT_UNDO_NON_ACTION: 'CANNOT_UNDO_NON_ACTION',
  ACTION_NOT_FOUND: 'ACTION_NOT_FOUND',
  UNABLE_TO_PERFORM_ACTION: 'UNABLE_TO_PERFORM_ACTION',
  DUPLICATED_ACTION: 'DUPLICATED_ACTION'
}

export const USER = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  MISSING_CREDENTIALS: 'MISSING_CREDENTIALS',
  VALID_PASSWORD_REQUIRED: 'VALID_PASSWORD_REQUIRED',
  PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  DUPLICATED_USER_INFORMATION: 'DUPLICATED_USER_INFORMATION'
}

export const POST = {
  POST_SLUG_REQUIRED: 'POST_SLUG_REQUIRED',
  POST_AUTHOR_REQUIRED: 'POST_AUTHOR_REQUIRED',
  POST_TITLE_REQUIRED: 'POST_TITLE_REQUIRED',
  POST_CONTENT_REQUIRED: 'POST_CONTENT_REQUIRED',
  CANNOT_SUBMIT_POST: 'CANNOT_SUBMIT_POST',
  POST_ALREADY_SUMMITED: 'POST_ALREADY_SUMMITED',
  POST_CANNOT_BE_RETRACTED: 'POST_CANNOT_BE_RETRACTED'
}

export const EVENT = {
  EVENT_SLUG_REQUIRED: 'EVENT_SLUG_REQUIRED',
  EVENT_AUTHOR_REQUIRED: 'EVENT_AUTHOR_REQUIRED',
  EVENT_TITLE_REQUIRED: 'EVENT_TITLE_REQUIRED',
  EVENT_CONTENT_REQUIRED: 'EVENT_CONTENT_REQUIRED',
  CANNOT_SUBMIT_EVENT: 'CANNOT_SUBMIT_EVENT',
  EVENT_ALREADY_SUMMITED: 'EVENT_ALREADY_SUMMITED',
  EVENT_CANNOT_BE_RETRACTED: 'EVENT_CANNOT_BE_RETRACTED'
}

export const COMMENT = {
  COMMENT_CREATOR_REQUIRED: 'COMMENT_CREATOR_REQUIRED',
  COMMENT_TARGET_REQUIRED: 'COMMENT_TARGET_REQUIRED',
  COMMENT_CONTENT_REQUIRED: 'COMMENT_CONTENT_REQUIRED'
}

export const PROGRESS = {
  ACTIVITY_IS_LOCKED: 'ACTIVITY_IS_LOCKED'
}